<a id="toc"></a>

# THEORY PANDAS-DataFrames:

- [pd.Series](#series) 

- [pd.DataFrame](#df)

- [IO](#io):
   - read_csv, read_excel, read_html, read_json (example: call api)
   - to_csv, to_json

- [OPERATIONS](#op):
   - +- <, add,multiply

- [INDEXING](#idx) :
    - at,loc, iat,iloc, boolean indexation, head, tail
    - series [] vs dataframe [[]]

- [ORDER BY](#sort)

- [USEFULL FUNCTIONS](#func)
    - isnull, fillna
    - drop
    - string methods
    - datetime/timestamp
        - timeindex
        - moving average 

- [AGGREGATION](#agg)

- [GROUPBY/PIVOT](#gb)
    - value_counts, groupby, pivot


- [JOINS & concat](#join)
    - merge

- [RESTRUCTURE](#restr)
    - get_dummies
    - (unpivot, unstack, explode,)

- [APPLY/MAP](#map)

Quick help
```python 
import pandas as pd
pd? 
```

official doc  
https://pandas.pydata.org/docs/index.html

comparison to sql  
https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_sql.html

In [1]:
import numpy as np
import pandas as pd

<a id="series"></a>

# pd.Series
[toc](#toc)

In [2]:
### first series: like numpy arrays and a dictionary
series = pd.Series(data=[0.25, 0.5, 0.75, 1.0])
print(series)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
series = pd.Series(data=[0.25, 0.5, 0.75, 1.0]
                   ,index=['a', 'b', 'c', 'd']
                   ,dtype=np.float32)
print(series)
print('-'*50)
series = pd.Series(data={'a':0.25, 'b': 0.5, 'c':0.75, 'd':1.0}, dtype = np.float32)
print(series)
print('-'*50)
series_cde = pd.Series(data=np.arange(3), index = list('cde'))
print(series_cde)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float32
--------------------------------------------------
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float32
--------------------------------------------------
c    0
d    1
e    2
dtype: int64

## Operations with series 
- like numpy

In [4]:
0.5*series + 1

a    1.125
b    1.250
c    1.375
d    1.500
dtype: float32

In [5]:
series <= 0.5

a     True
b     True
c    False
d    False
dtype: bool


**Operations between two "pd.Series" return values only their matching indices**

In [6]:
print(series+series_cde)

a     NaN
b     NaN
c    0.75
d    2.00
e     NaN
dtype: float64

In [7]:
print(series.add(other=series_cde,fill_value=0))

a    0.25
b    0.50
c    0.75
d    2.00
e    2.00
dtype: float64

<a id="df"></a>

# pd.DataFrame
[toc](#toc)

In [8]:
series_1 = pd.Series(data=np.random.randint(5,size=(5),dtype=np.uint8),
                    index=list('abcde'))

series_a = pd.Series(data=list('abcab'),
                     index=list('abcde'),
                     dtype='category')

series_b = pd.Series(data=list('xyzzz'),
                     index=list('abcde'),
                     dtype='O'
                    )


series_2 = pd.Series([1,1,1,0,np.nan], 
                     index = list('abcde'))

df = pd.DataFrame(data = {'num':series_1,'cat':series_a,'cat2':series_b,'num2':series_2})
print(df)
display(df)

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

In [9]:

df1 = pd.DataFrame(data = {'A':[1,2,3], 'B':[3,2,1], 'C':[4,5,6]})
df1

   A  B  C
0  1  3  4
1  2  2  5
2  3  1  6

In [10]:
df2 = pd.DataFrame(data = np.random.randint(2,10,size=(8,3)),columns = list('ABC'))
df2

   A  B  C
0  8  2  3
1  8  5  9
2  9  3  6
3  6  6  4
4  9  8  2
5  3  4  2
6  9  7  5
7  6  4  7

In [11]:
df3 = pd.DataFrame(data = [{'i':1, 'j':5}, {'i':2,'k':3},{'i':6,'j':2,'k':7}])
df3

   i    j    k
0  1  5.0  NaN
1  2  NaN  3.0
2  6  2.0  7.0

## datatypes

https://pandas.pydata.org/docs/reference/arrays.html

## attributes

In [12]:
df.shape

(5, 4)

In [13]:
df.dtypes

num        uint8
cat     category
cat2      object
num2     float64
dtype: object

In [14]:
df['cat'] ## known possible/autorized values -->  less flexible, more efficient

a    a
b    b
c    c
d    a
e    b
Name: cat, dtype: category
Categories (3, object): ['a', 'b', 'c']

In [15]:
df["cat2"] ## object = 'python object', anything possible --> more flexible, less efficient

a    x
b    y
c    z
d    z
e    z
Name: cat2, dtype: object

In [16]:
df.columns

Index(['num', 'cat', 'cat2', 'num2'], dtype='object')

In [17]:
df.values

array([[2, 'a', 'x', 1.0],
       [1, 'b', 'y', 1.0],
       [2, 'c', 'z', 1.0],
       [4, 'a', 'z', 0.0],
       [0, 'b', 'z', nan]], dtype=object)

In [18]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [19]:
list(df.items())

[('num',
  a    2
  b    1
  c    2
  d    4
  e    0
  Name: num, dtype: uint8),
 ('cat',
  a    a
  b    b
  c    c
  d    a
  e    b
  Name: cat, dtype: category
  Categories (3, object): ['a', 'b', 'c']),
 ('cat2',
  a    x
  b    y
  c    z
  d    z
  e    z
  Name: cat2, dtype: object),
 ('num2',
  a    1.0
  b    1.0
  c    1.0
  d    0.0
  e    NaN
  Name: num2, dtype: float64)]

In [20]:
for col_name,series in df.items():
    print(col_name)
    print(series)
    print('-'*50)
    for row in series:
        print(row)
    break

num
a    2
b    1
c    2
d    4
e    0
Name: num, dtype: uint8
--------------------------------------------------
2
1
2
4
0

<a id="io"></a>
# IO
[toc](#toc)

### Read and write CSV is very easy with Pandas !
- it is as easy for other data formats too

In [21]:
df.to_csv('my_df.csv',index=False,sep=';')

In [22]:
df_from_csv = pd.read_csv('my_df.csv', sep=';')
df_from_csv

   num cat cat2  num2
0    2   a    x   1.0
1    1   b    y   1.0
2    2   c    z   1.0
3    4   a    z   0.0
4    0   b    z   NaN

In [23]:
### prereq : install beautifull soup 4 (bs4) or lxml
try:
    url = 'https://fr.wikipedia.org/wiki/Liste_des_villes_de_Belgique'

    ### fetch all "HTML tables" pandas can find on this url
    list_of_dfs = pd.read_html(url) ## requires internet connection
    display(list_of_dfs[1]) ## the most interesting table on this page 
    
except Exception as err:
    print("install beautifull soup 4 (bs4) or lxml ?")
    print("-"*50)
    print(err)

,Ville,Arrondissement,Province,Habitants de la commune (2025),Année de l'acte,Charte communale
0,Aerschot (Aarschot),Louvain (Leuven),Province du Brabant flamand,31 495,1825,1194
1,Alost (Aalst),Alost (Aalst),Province de Flandre-Orientale,92 066,1825,1174
2,Andenne,Namur,Province de Namur,28 226,1825,NaN
3,Ans,Liège,Province de Liège,29 099,2021[3],NaN
4,Antoing,Tournai,Province de Hainaut,7 533,1825,1817 (titre)
...,...,...,...,...,...,...
132,Waremme,Waremme,Province de Liège,15 364,1985,NaN
133,Wavre,Nivelles,Province du Brabant wallon,35 564,1825,1222
134,Wervicq (Wervik),Ypres,Province de Flandre-Occidentale,19 200,1825,NaN
135,Ypres (Ieper),Ypres,Province de Flandre-Occidentale,35 573,1825,1174
136,Zottegem,Alost,Province de Flandre-Orientale,28 213,1985,NaN

In [81]:
try:
    ### create/write/connect to an Excel
    EW = pd.ExcelWriter(path='my_new_excel.xlsx')
    
    df_from_csv.to_excel(excel_writer=EW, sheet_name='from csv to excel')
    
    EW.close()
except Exception as err:
    print(err)

In [25]:
### pd.read_json() see doc: https://pandas.pydata.org/docs/reference/api/pandas.read_json.html

<a id="io"></a>
# Operations
[toc](#toc)

In [26]:
try:
    display(df+1)
except Exception as err:
    print(err)

unsupported operand type(s) for +: 'Categorical' and 'int'

In [27]:
df1+100

     A    B    C
0  101  103  104
1  102  102  105
2  103  101  106

In [28]:
df1<5

      A     B      C
0  True  True   True
1  True  True  False
2  True  True  False

In [29]:
df1+df2

      A    B     C
0   9.0  5.0   7.0
1  10.0  7.0  14.0
2  12.0  4.0  12.0
3   NaN  NaN   NaN
4   NaN  NaN   NaN
5   NaN  NaN   NaN
6   NaN  NaN   NaN
7   NaN  NaN   NaN

In [30]:
df1.add(other=df2, fill_value=0)

      A    B     C
0   9.0  5.0   7.0
1  10.0  7.0  14.0
2  12.0  4.0  12.0
3   6.0  6.0   4.0
4   9.0  8.0   2.0
5   3.0  4.0   2.0
6   9.0  7.0   5.0
7   6.0  4.0   7.0

In [31]:
display(df1)
np.exp(df1)-1 ## numpy fonctions are compatible

   A  B  C
0  1  3  4
1  2  2  5
2  3  1  6

           A          B           C
0   1.718282  19.085537   53.598150
1   6.389056   6.389056  147.413159
2  19.085537   1.718282  402.428793

<a id="idx"></a>
# Indexing & co
[toc](#toc)

## simple indexing: columns only

In [32]:
## simple indexing
print(type(df['cat']))

print('-'*50)
print(df['cat']) ## return series
print(df.cat) ## return series

<class 'pandas.core.series.Series'>
--------------------------------------------------
a    a
b    b
c    c
d    a
e    b
Name: cat, dtype: category
Categories (3, object): ['a', 'b', 'c']
a    a
b    b
c    c
d    a
e    b
Name: cat, dtype: category
Categories (3, object): ['a', 'b', 'c']

## SELECT...FROM...WHERE... : at,loc & iat,iloc
- works like a "SELECT ... FROM ... WHERE" in SQL

```sql
SELECT my_column_1, my_column_2
FROM my_table
WHERE index IN (2,3,4)
```  
becomes      
```python
my_table.loc[[2,3,4], ["my_column_1","my_column_2"]]
```

In [33]:
### row 'a', column 'num'
display(df.loc['a','num']) ## return value
display(df.at['a','num']) ## faster, but one cell only
print('-'*50)

### all rows, 'cat' column
display(df.loc[:,'cat']) ## return series

print('-'*50)

### row 'a', all columns
display(df.loc['a',:]) ## return series

print('-'*50)
### rows ['a','c'], columns ['num','num2']
display(df.loc[['a','c'],['num','num2']]) ## return dataframe

np.uint8(2)

np.uint8(2)

--------------------------------------------------

a    a
b    b
c    c
d    a
e    b
Name: cat, dtype: category
Categories (3, object): ['a', 'b', 'c']

--------------------------------------------------

num       2
cat       a
cat2      x
num2    1.0
Name: a, dtype: object

--------------------------------------------------

   num  num2
a    2   1.0
c    2   1.0

In [34]:
### row 0, column 1
display(df.iloc[0,1]) ## return value
display(df.iat[0,1])
print('-'*50)

### row 0, all columns
display(df.iloc[0,:]) ## return series
print('-'*50)

### all rows, columns 1
display(df.iloc[:,1]) ## return series
print('-'*50)

### rows [0,1] , columns [1,2]
display(df.iloc[[0,1],[1,2]]) ## return dataframe

'a'

'a'

--------------------------------------------------

num       2
cat       a
cat2      x
num2    1.0
Name: a, dtype: object

--------------------------------------------------

a    a
b    b
c    c
d    a
e    b
Name: cat, dtype: category
Categories (3, object): ['a', 'b', 'c']

--------------------------------------------------

  cat cat2
a   a    x
b   b    y

## Boolean indexing

In [35]:
cond = df['cat'].isin(['a','c'])
df.loc[cond,:]

   num cat cat2  num2
a    2   a    x   1.0
c    2   c    z   1.0
d    4   a    z   0.0

In [36]:
cond

a     True
b    False
c     True
d     True
e    False
Name: cat, dtype: bool

In [37]:
cond1 = df['num2']>0
df.loc[cond1,:]

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0

In [38]:
df.loc[cond1 & ~cond,:] ### &= "AND" , | = "OR" , ~ = NOT

   num cat cat2  num2
b    1   b    y   1.0

## head,tail

In [39]:
df.head(2)

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0

## WARNING : Series \[\] vs DataFrame \[\[\]\]

In [40]:
### indexing 1 value for columns
df.loc[:,'cat'] ## series

a    a
b    b
c    c
d    a
e    b
Name: cat, dtype: category
Categories (3, object): ['a', 'b', 'c']

In [41]:
### slincing a list of columns
display(df.loc[:,['cat']]) ## dataframe

print(df.loc[:,['cat']])

df[['cat']] # dataframe
df['cat'] # Series

  cat
a   a
b   b
c   c
d   a
e   b

  cat
a   a
b   b
c   c
d   a
e   b

<a id="sort"></a>
# Order by
[toc](#toc)

In [42]:
df['num'].sort_values(ascending=False)

d    4
a    2
c    2
b    1
e    0
Name: num, dtype: uint8

In [43]:
df.sort_values(by=['num','num2'],ascending=[False,True])

   num cat cat2  num2
d    4   a    z   0.0
a    2   a    x   1.0
c    2   c    z   1.0
b    1   b    y   1.0
e    0   b    z   NaN

<a id="func"></a>

# Usefull functions and methods
[toc](#toc)

## uniques, isnull, fillna, drop, replace

In [44]:
df

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

In [45]:
df.median(numeric_only=True)

num     2.0
num2    1.0
dtype: float64

In [46]:
### unique
print("unique:")
display(df['cat'].unique())


### isna, isnull
print('-'*50)
print('isna,isnull:')
display(df.isna()) ## alias of isnull

### fillna
print('-'*50)
print('fillna:')
display(df.fillna(df.median(numeric_only=True))) 
#df.fillna(np.inf, inplace = True) ## inplace=True => modify directly the dataframe

### drop
print('-'*50)
print('drop, dropna:')

df['static'] = 1
display(df)

df.drop(columns=['static'], inplace=True)
display(df)

unique:

['a', 'b', 'c']
Categories (3, object): ['a', 'b', 'c']

--------------------------------------------------
isna,isnull:

     num    cat   cat2   num2
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d  False  False  False  False
e  False  False  False   True

--------------------------------------------------
fillna:

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   1.0

--------------------------------------------------
drop, dropna:

   num cat cat2  num2  static
a    2   a    x   1.0       1
b    1   b    y   1.0       1
c    2   c    z   1.0       1
d    4   a    z   0.0       1
e    0   b    z   NaN       1

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

<a id="agg"></a>
# Aggregation
[toc](#toc)

In [47]:
### sum,mean, (count,) ,std, median, quantile,...
print(df.mean(numeric_only=True)) ## ignore non-numeric columns/values
print('-'*50)
print(df1.sum(axis=0)) ## return series
print(df1.sum(axis=1)) ## return series
print('-'*50)
print(df1.sum().sum()) ## return (series.sum()) --> value

num     1.80
num2    0.75
dtype: float64
--------------------------------------------------
A     6
B     6
C    15
dtype: int64
0     8
1     9
2    10
dtype: int64
--------------------------------------------------
27

In [48]:
### mixed aggregations
df1.agg({'A':'sum','B':"mean"})

A    6.0
B    2.0
dtype: float64

In [49]:
df1.agg({'A':['sum','mean'],'B':['count','mean',]})

         A    B
sum    6.0  NaN
mean   2.0  2.0
count  NaN  3.0

In [50]:
df1.nunique()

A    3
B    3
C    3
dtype: int64

In [51]:
df1['A'].unique()

array([1, 2, 3])

### descriptive statistics

In [52]:
df.describe() #include='all')

           num  num2
count  5.00000  4.00
mean   1.80000  0.75
std    1.48324  0.50
min    0.00000  0.00
25%    1.00000  0.75
50%    2.00000  1.00
75%    2.00000  1.00
max    4.00000  1.00

<a id="gb"></a>
# Groupby & co
[toc](#toc)

## value counts

In [53]:
VC = df.value_counts('cat') ### groupby count
#VC = df['cat'].value_counts()
VC

cat
a    2
b    2
c    1
Name: count, dtype: int64

## groupby

In [54]:
GB = df.groupby('cat2').count()

display(GB)

print(GB.index)
print(GB.columns)

      num  cat  num2
cat2
x       1    1     1
y       1    1     1
z       3    3     2

Index(['x', 'y', 'z'], dtype='object', name='cat2')
Index(['num', 'cat', 'num2'], dtype='object')

In [55]:
GB_no_index = df.groupby(by=['cat2'], as_index=False).count()
display(GB_no_index)

  cat2  num  cat  num2
0    x    1    1     1
1    y    1    1     1
2    z    3    3     2

In [56]:
GB = df.groupby('cat2').agg({'num':['sum','count'],'num2':'mean'})
display(GB)
#print(GB.index)
print(GB.columns)

     num       num2
     sum count mean
cat2
x      2     1  1.0
y      1     1  1.0
z      6     3  0.5

MultiIndex([( 'num',   'sum'),
            ( 'num', 'count'),
            ('num2',  'mean')],
           )

In [57]:
GB.loc[:, ('num','sum')]

cat2
x    2
y    1
z    6
Name: (num, sum), dtype: uint8

In [58]:
GB2 = GB.copy()
GB2.columns = ['num_sum','num_count','num2_mean']
GB2

      num_sum  num_count  num2_mean
cat2
x           2          1        1.0
y           1          1        1.0
z           6          3        0.5

In [59]:
GB3 = GB2.copy().reset_index()
GB3

  cat2  num_sum  num_count  num2_mean
0    x        2          1        1.0
1    y        1          1        1.0
2    z        6          3        0.5

In [60]:
### watch out for categories !
df[['cat','cat2']].dtypes

cat     category
cat2      object
dtype: object

In [61]:
### "observed" parameter is mandatory for "category" datatypes
try:
    GB_ = df.groupby(by= 'cat').agg({'num':'sum'})
    print(GB_)
except Exception as err:
    print(err)

print("-"*50)
GB__ = df.groupby(by= 'cat', observed=True).agg({'num':'sum'})
GB__

     num
cat
a      6
b      1
c      2
--------------------------------------------------

C:\Users\cedri\AppData\Local\Temp\ipykernel_17592\3575154791.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  GB_ = df.groupby(by= 'cat').agg({'num':'sum'})

     num
cat
a      6
b      1
c      2

## pivot table

In [62]:
df4 = df.copy()
#df4['cat3']=np.random.choice(list('ij'),size=(df.shape[0]))
df4

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

In [82]:
pt = df4.pivot_table(index='cat',columns='cat2',aggfunc='sum',observed=False)
pt

     num       num2
cat2   x  y  z    x    y    z
cat
a      2  0  4  1.0  0.0  0.0
b      0  1  0  0.0  1.0  0.0
c      0  0  2  0.0  0.0  1.0

<a id="join"></a>
# Joins
[toc](#toc)

In [64]:
series_ = pd.Series(data=[1,2,3],
                    index= np.random.choice(['a','b'],size=(3)))
df5 = series_.to_frame()
display(df5)
display(df)

   0
a  1
a  2
a  3

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

In [65]:
df.merge(df5, left_index=True, right_index=True, how='inner')

   num cat cat2  num2  0
a    2   a    x   1.0  1
a    2   a    x   1.0  2
a    2   a    x   1.0  3

In [66]:
pd.merge(df,df5, left_on='cat', right_index=True, how='inner')

   num cat cat2  num2  0
a    2   a    x   1.0  1
a    2   a    x   1.0  2
a    2   a    x   1.0  3
d    4   a    z   0.0  1
d    4   a    z   0.0  2
d    4   a    z   0.0  3

# Concatenate
[toc](#toc)

In [67]:
display(df1)
display(df2)
display(df3)

   A  B  C
0  1  3  4
1  2  2  5
2  3  1  6

   A  B  C
0  8  2  3
1  8  5  9
2  9  3  6
3  6  6  4
4  9  8  2
5  3  4  2
6  9  7  5
7  6  4  7

   i    j    k
0  1  5.0  NaN
1  2  NaN  3.0
2  6  2.0  7.0

In [68]:

df_concat = pd.concat([df1,df2],
                      axis=0,  ## along rows
                      ignore_index=False
                     )
#df_concat = pd.concat([df1,df2])
display(df_concat)
display(df_concat.loc[0,:])

print('-'*50)
df_concat = pd.concat([df1,df3],
                      axis=1    ## along columns
                     ) 
display(df_concat)

   A  B  C
0  1  3  4
1  2  2  5
2  3  1  6
0  8  2  3
1  8  5  9
2  9  3  6
3  6  6  4
4  9  8  2
5  3  4  2
6  9  7  5
7  6  4  7

   A  B  C
0  1  3  4
0  8  2  3

--------------------------------------------------

   A  B  C  i    j    k
0  1  3  4  1  5.0  NaN
1  2  2  5  2  NaN  3.0
2  3  1  6  6  2.0  7.0

<a id="restr"></a>
# Restructure table
[toc](#toc)

## get_dummies
OneHot Encoding

In [69]:
display(df)
gd = pd.get_dummies(df)
gd

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

   num  num2  cat_a  cat_b  cat_c  cat2_x  cat2_y  cat2_z
a    2   1.0   True  False  False    True   False   False
b    1   1.0  False   True  False   False    True   False
c    2   1.0  False  False   True   False   False    True
d    4   0.0   True  False  False   False   False    True
e    0   NaN  False   True  False   False   False    True

## unpivot +-= melt

In [70]:

up = gd.melt(['num','num2'])
display(up)
up = up.loc[up['value']!=0]
up

    num  num2 variable  value
0     2   1.0    cat_a   True
1     1   1.0    cat_a  False
2     2   1.0    cat_a  False
3     4   0.0    cat_a   True
4     0   NaN    cat_a  False
5     2   1.0    cat_b  False
6     1   1.0    cat_b   True
7     2   1.0    cat_b  False
8     4   0.0    cat_b  False
9     0   NaN    cat_b   True
10    2   1.0    cat_c  False
11    1   1.0    cat_c  False
12    2   1.0    cat_c   True
13    4   0.0    cat_c  False
14    0   NaN    cat_c  False
15    2   1.0   cat2_x   True
16    1   1.0   cat2_x  False
17    2   1.0   cat2_x  False
18    4   0.0   cat2_x  False
19    0   NaN   cat2_x  False
20    2   1.0   cat2_y  False
21    1   1.0   cat2_y   True
22    2   1.0   cat2_y  False
23    4   0.0   cat2_y  False
24    0   NaN   cat2_y  False
25    2   1.0   cat2_z  False
26    1   1.0   cat2_z  False
27    2   1.0   cat2_z   True
28    4   0.0   cat2_z   True
29    0   NaN   cat2_z   True

    num  num2 variable  value
0     2   1.0    cat_a   True
3     4   0.0    cat_a   True
6     1   1.0    cat_b   True
9     0   NaN    cat_b   True
12    2   1.0    cat_c   True
15    2   1.0   cat2_x   True
21    1   1.0   cat2_y   True
27    2   1.0   cat2_z   True
28    4   0.0   cat2_z   True
29    0   NaN   cat2_z   True

## explode

In [71]:
df7 = pd.DataFrame(data={'A':[[1,2],[2,3],[4,5]],'B':[['a','b'],['c','d'],['e','f']]})
df7

        A       B
0  [1, 2]  [a, b]
1  [2, 3]  [c, d]
2  [4, 5]  [e, f]

In [72]:
df7.explode(['A'])

   A       B
0  1  [a, b]
0  2  [a, b]
1  2  [c, d]
1  3  [c, d]
2  4  [e, f]
2  5  [e, f]

In [73]:
### joined explosion of values
df7.explode(['A','B'])

   A  B
0  1  a
0  2  b
1  2  c
1  3  d
2  4  e
2  5  f

<a id="map"></a>
# Apply&map
[toc](#toc)

## map
on series (or df)

In [74]:
def my_funct(x,val=0):
    
    if x < val:
        return -1
    elif x > val:
        return +1
    else:
        #print(x)
        return 0

df8= df.copy()

df8['res'] = df8['num2'].map(my_funct) 
display(df8)

   num cat cat2  num2  res
a    2   a    x   1.0    1
b    1   b    y   1.0    1
c    2   c    z   1.0    1
d    4   a    z   0.0    0
e    0   b    z   NaN    0

## apply
more complex version of 'map';  
on row/column of df,  
passing arguments

In [75]:
display(df)
print('-'*50)
print(df['num'].apply(my_funct,args=(2,)))

print(df['num'].apply(my_funct, **{'val':2}))

   num cat cat2  num2
a    2   a    x   1.0
b    1   b    y   1.0
c    2   c    z   1.0
d    4   a    z   0.0
e    0   b    z   NaN

--------------------------------------------------
a    0
b   -1
c    0
d    1
e   -1
Name: num, dtype: int64
a    0
b   -1
c    0
d    1
e   -1
Name: num, dtype: int64

In [76]:

def my_funct2 (x):
    return pd.isnull(x).sum()

print(df.apply(my_funct2,axis=0))
print(df.apply(my_funct2,axis=1))

num     0
cat     0
cat2    0
num2    1
dtype: int64
a    0
b    0
c    0
d    0
e    1
dtype: int64

### rewrite your problem to prevent use of apply/map

In [77]:
### vectorisation : faster alernative: recommended
### require to think the problem differently than "for each line"
def my_funct_2(series, val=0.5):
    cond1 = series<val
    cond2 = series>val
    return -1*cond1 + cond2

my_funct_2(df['num'],val=0.75)

a    1
b    1
c    1
d    1
e   -1
Name: num, dtype: int64

### benchmarks

In [78]:
series_rdm = pd.Series(np.random.randint(0,10,1_000_000))
series_rdm

0         6
1         1
2         2
3         5
4         2
         ..
999995    2
999996    4
999997    8
999998    2
999999    8
Length: 1000000, dtype: int32

In [79]:
%timeit series_rdm.apply(my_funct, val=5)

1.38 s ± 114 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [80]:
%timeit my_funct_2(series_rdm,val=5)

15.9 ms ± 993 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)