**<p style="text-align:center; font-size:30px"><u> Exercices de base numpy</u></p>**

In [1]:
import numpy as np

# Exercice 1
- créez un numpy array depuis la liste suivante [11.7, 20, 325, 10.2, 11.7, 20]
- remplacez la première occurence de la valeur 11.7 par 5
- remplacez toutes les occurences des valeurs 20 par 0
- calculez la taille (mémoire) du tableau
- modifier le typage en uint8
- calculez la taille du tableau
- Observez les valeurs ? Que s'est-il passé ?

<br>

In [2]:
arr = np.array([11.7, 20, 325, 10.2, 11.7, 20])

## version simpliste, car on connait la liste
#arr[0] = 5



cond = arr == 11.7
print(arr[cond])

### ne fonctionne pas/plus
arr[cond][0] = 5

### fonctionne
first_where_valid = np.argmax(arr==11.7)
arr[first_where_valid] = 5
print(arr)
## -----

### version compliqué, mais plus générale
# i0= np.argwhere(arr==11.7) # les pos ou condition est valide
# print(i0)
# arr[i0[0]] = 0.05
# print(arr)

arr[arr == 20] = 0 ## indexation Booléene

print(arr)
print(arr.nbytes)

print('-'*30)
## -- modif

arr = arr.astype(np.uint8)
arr = np.array(arr, dtype=np.uint8)
print(arr.nbytes)

print(arr)

[11.7 11.7]
[  5.   20.  325.   10.2  11.7  20. ]
[  5.    0.  325.   10.2  11.7   0. ]
48
------------------------------
6
[ 5  0 69 10 11  0]

In [3]:
arr==0

array([False,  True, False, False, False,  True])

In [4]:
arr[arr==0]

array([0, 0], dtype=uint8)

In [5]:
arr = np.array([11.7, 20, 325, 10.2, 11.7, 20])
print(np.where(arr==20))

print(np.argwhere(arr==20))

(array([1, 5]),)
[[1]
 [5]]

Le typage en uint 8 implique que le plage des valeurs ne peut s'étendre qu'entre 0 et 255. Toutes valeurs en dehors de cette plage ne génèrent pas d'erreur.

Elles sont ramenées entre les deux bornes à l'aide du modulo.

<br>

In [6]:
arr = np.array([384, 254, 798], dtype=np.int32)
display(arr)

display(arr.astype(np.uint8))

display(arr%256)

array([384, 254, 798], dtype=int32)

array([128, 254,  30], dtype=uint8)

array([128, 254,  30], dtype=int32)

In [7]:
2**8 #255 bit => 1111 1111 

# 0 = 0000 0000
# 1 = 0000 0001
# 2 = 0000 0010
# 3 = 0000 0011

256

## Indexation Booléene

- soit deux vecteurs représentant les notes(sur 20) en français d'une classe:
  ```py 
  [10, 15, 2, 10, 8]
  ```
  ```py 
  ['bob', 'alice', 'john', 'marie', 'pierre']
  ```
  - Affichez les noms des élèves en échec

<br>

In [8]:
notes = np.array([10, 15, 2, 10, 8])
students = np.array(['bob', 'alice', 'john', 'marie', 'pierre'])

### | or, & and

In [9]:
students[(notes < 10)|(notes==10)]  ## <= better !

array(['bob', 'john', 'marie', 'pierre'], dtype='<U6')

# Exercice 2

- créez un numpy array depuis la matrice suivante [[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]]
- affichez:
  - le type de données de la matrice
  - sa forme
  - son nombre de dimension
  - son nombre d'élément
  - Depuis la forme, pouvez-vous obtenir le nombre de dimension et le nombre d'élément ?
- multipliez la dernière colonne par 5 et divisez la première ligne par 0
- modifier le typage en int. Que se passe-t-il ?

<br>

In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, np.nan]])

print(f'dtype: {arr.dtype}\nshape: {arr.shape}\nndim: {arr.ndim}\nsize: {arr.size}')

dtype: float64
shape: (3, 3)
ndim: 2
size: 9

In [11]:
var = 5
s = "my string "+ str(var)
s2 = f"my string {var}"
print(s)
print(s2)

my string 5
my string 5

In [12]:
print(type(np.nan))
np.nan is None

<class 'float'>

False

In [13]:
ndim = len(arr.shape)
size =1
for i in arr.shape:
    size *= i
    
size_ = np.prod(arr.shape) # np.product()

print(size_,size)

9 9

In [14]:
print(arr,'\n','-'*30)

arr[:, -1] *= 5 #= arr[:, -1]*5
print(arr)

print('-'*30)

arr[0,:] = arr[0,:]/0
print(arr)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. nan]]
 ------------------------------
[[ 1.  2. 15.]
 [ 4.  5. 30.]
 [ 7.  8. nan]]
------------------------------
[[inf inf inf]
 [ 4.  5. 30.]
 [ 7.  8. nan]]

C:\Users\cedri\AppData\Local\Temp\ipykernel_30424\2719287679.py:8: RuntimeWarning: divide by zero encountered in divide
  arr[0,:] = arr[0,:]/0

In [15]:
np.exp(-np.inf)

np.float64(0.0)

# warning numpy

In [16]:

#----
np.seterr(divide='ignore', invalid='ignore')

print('ignore\n')
a = np.arange(5)

b = 5/a
print(b)
c = a/a
print(c)

print('-'*30)
#----
np.seterr(divide='warn', invalid='warn')
print('warn\n')
b = 5/a
print(b)
c = a/a
print(c)
print('-'*30)
#----
np.seterr(divide='ignore', invalid='raise')
print('raise\n')
b = 5/a 
print(b)
'''c = a/a ## raise error'''
print(c)
print('-'*30)

ignore

[       inf 5.         2.5        1.66666667 1.25      ]
[nan  1.  1.  1.  1.]
------------------------------
warn

[       inf 5.         2.5        1.66666667 1.25      ]
[nan  1.  1.  1.  1.]
------------------------------
raise

[       inf 5.         2.5        1.66666667 1.25      ]
[nan  1.  1.  1.  1.]
------------------------------

C:\Users\cedri\AppData\Local\Temp\ipykernel_30424\172693283.py:16: RuntimeWarning: divide by zero encountered in divide
  b = 5/a
C:\Users\cedri\AppData\Local\Temp\ipykernel_30424\172693283.py:18: RuntimeWarning: invalid value encountered in divide
  c = a/a

In [17]:
np.seterr(divide='warn', invalid='warn')

{'divide': 'ignore', 'over': 'warn', 'under': 'ignore', 'invalid': 'raise'}

# end warning

In [18]:
display(arr)
arr_ = arr.astype(int)
print(arr_)
arr_.dtype

array([[inf, inf, inf],
       [ 4.,  5., 30.],
       [ 7.,  8., nan]])

[[-9223372036854775808 -9223372036854775808 -9223372036854775808]
 [                   4                    5                   30]
 [                   7                    8 -9223372036854775808]]

C:\Users\cedri\AppData\Local\Temp\ipykernel_30424\939719749.py:2: RuntimeWarning: invalid value encountered in cast
  arr_ = arr.astype(int)

dtype('int64')

In [19]:
arr__ = arr.astype(np.int_)
print(arr__)
arr__.dtype

[[-9223372036854775808 -9223372036854775808 -9223372036854775808]
 [                   4                    5                   30]
 [                   7                    8 -9223372036854775808]]

C:\Users\cedri\AppData\Local\Temp\ipykernel_30424\4159571076.py:1: RuntimeWarning: invalid value encountered in cast
  arr__ = arr.astype(np.int_)

dtype('int64')

# Exercice 3

Exercice:
1. Créer la matrice suivante dans la variable x1:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire une partie de x1 dans la variable x2
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x2 par 99
4. Réafficher x1

In [20]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
x1 = np.arange(10,100,10).reshape(3,3)
print(x1)

print('-'*30)

x2 = x1[1:,1:] ## une vue: fait référence au même objet
print(x2)

print('-'*30)

x2[0,0] = 99
print(x2)

print('-'*30)

print(x1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
------------------------------
[[50 60]
 [80 90]]
------------------------------
[[99 60]
 [80 90]]
------------------------------
[[10 20 30]
 [40 99 60]
 [70 80 90]]

# Exercice 4

Exercice:
1. Créer la matrice suivante dans la variable x3:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire __une copie__ d'une partie de x3 dans la variable x4
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x2 par 99
4. Réafficher x1

In [22]:
x3 = np.arange(10,100,10).reshape(3,3)
print(x3)

print('-'*30)
# from copy import deepcopy ## pas nécéssaire

x4 = x3[1:,1:].copy()
print(x4)

print('-'*30)

x4[0,0] = 99
print(x4)

print('-'*30)

print(x3)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
------------------------------
[[50 60]
 [80 90]]
------------------------------
[[99 60]
 [80 90]]
------------------------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]

# Exercice 5

- créez une matrice (4*4) remplie de valeurs aléatoires comprises entre 2 et 8
- créer un matrice d'identité (*i.e.* une matrice carrée dont la diagonale descendente principale est remplie de 1 et le reste = 0). Proposez plusieurs solutions
- créer une matrice dont la diagonale principale sera remplie de 6 valeurs aléatoires. Proposez plusieurs solutions

(tip: 'zeros','identity', 'fill_diagonal')
<br>

In [23]:
arr = np.random.randint(2, 9, (4, 4))
print(arr)

print('-'*30)

[[4 7 2 7]
 [5 3 2 7]
 [6 6 8 8]
 [2 5 6 7]]
------------------------------

In [24]:
## diag v0
identity = np.zeros((5, 5), dtype=np.int32)

for i in range(identity.shape[0]):
    identity[i, i] = 1

identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [25]:
## diag v1
identity = np.zeros((5, 5), dtype=np.int32)
# np.fill_diagonal does not return a view

np.fill_diagonal(identity, 1)

identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [26]:
## diag v2
## much faster
np.identity(5, dtype=np.int32)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [27]:
size = 6
diag = np.random.randint(0, 20, 6)
arr = np.zeros((size, size), dtype=np.int32)

for idx, val in enumerate(diag):
    arr[idx, idx] = val
arr

array([[12,  0,  0,  0,  0,  0],
       [ 0, 19,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0],
       [ 0,  0,  0, 10,  0,  0],
       [ 0,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0, 11]], dtype=int32)

In [28]:
size = 6
diag = np.random.randint(0, 20, 6)
arr = np.zeros((size, size), dtype=np.int32)

np.fill_diagonal(arr, diag)
arr

array([[ 7,  0,  0,  0,  0,  0],
       [ 0, 19,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0],
       [ 0,  0,  0, 14,  0,  0],
       [ 0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0, 10]], dtype=int32)

# Exercice 6

- reproduire la matrice suivante (sans les noms de colonnes et d'index)
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>10€</td>
      <td>30€</td>
      <td>5€</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>20€</td>
      <td>50€</td>
      <td>1€</td>
    </tr>
    <tr>
      <th>john</th>
      <td>15€</td>
      <td>30€</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

- affichez le montant total des achats
- affichez les totaux des achats par personne
- affichez les moyennes des achats par type d'aliments

<br>

In [42]:
arr = np.array([
    [10, 30, 5],
    [20, 50, 1],
    [15, 30, np.nan]
])

## affichez le montant total des achats
print(arr)
print('-'*30)
print('sum',np.sum(arr)) # version fonction: nan-sensitive
print('nansum',np.nansum(arr))# version fonction: nan-safe
print('-'*30)
print('sum oo',arr.sum()) # version OO : nan-sensitive

print('-'*30)

[[10. 30.  5.]
 [20. 50.  1.]
 [15. 30. nan]]
------------------------------
sum nan
nansum 161.0
------------------------------
sum oo nan
------------------------------

### x = = np.nan ==> np.isnan(x)
Il faut absolument utiliser la fonction np.isnan pour identifier les nan dans un numpy array et les modifier.

Autrement dit, la solution suivante ne fonctionne pas:

```py
arr[arr == np.nan]
```

<br>

In [30]:
### ici on aurait voulu remplacer les 'nan' par '0'
print(np.isnan(arr)) ## j'ai besoin de np.isnan()
print('-'*30)
arr_ = arr.copy() 
arr_[np.isnan(arr_)] = 0 # indexation booléenne(Vrai/Faux)
# changer toutes les valeurs, WHERE isnan==True

print(arr_)
print('-'*30)
print(arr_.sum())

[[False False False]
 [False False False]
 [False False  True]]
------------------------------
[[10. 30.  5.]
 [20. 50.  1.]
 [15. 30.  0.]]
------------------------------
161.0

In [31]:
"""
affichez les totaux des achats par personne

affichez les moyennes des achats par type d'aliments
"""

print('nan-sensitive')
print(np.sum(arr, axis=1)) #aggr. sur l'axe =1: résultat par personne
print(np.mean(arr, axis=0)) #aggr. sur l'axe =0: résultat par produit
print('-'*30)
print(arr)
print('-'*30)
print('nan-safe')
print((np.nansum(arr, axis=1,keepdims=True)))# .reshape(3,1)) #aggr. sur l'axe =1: résultat par personne
print((np.nanmean(arr, axis=0)).reshape(1,3)) #aggr. sur l'axe =0: résultat par produit

nan-sensitive
[45. 71. nan]
[15.         36.66666667         nan]
------------------------------
[[10. 30.  5.]
 [20. 50.  1.]
 [15. 30. nan]]
------------------------------
nan-safe
[[45.]
 [71.]
 [45.]]
[[15.         36.66666667  3.        ]]

In [32]:
### Einstein Summation
### affichez les totaux des achats par personne

arr2 = np.einsum('ij->i',arr)
print(arr2)

[45. 71. nan]

In [33]:

### affichez les moyennes des achats par type d'aliments
arr2 = np.einsum('ij->j',arr)
print(arr2)

[ 45. 110.  nan]

In [34]:
## version algo: à éviter, 
## utiliser de préférence les fonctions des librairies/modules (=optimisé)

In [35]:
### affichez les totaux des achats par personne
somme_pers = np.zeros(3) ### initialisation de la structure (avec valeur = 0)
                         ###['bob', 'alice', 'john']
for j in range(3):## iterer sur chaque colonne
    somme_pers += arr[:,j] ## somme des valeur de la colonne pour bob,alice, john
print(somme_pers)

[45. 71. nan]

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
for i in range(3):
    print(np.nansum(arr[i,:]))

45.0
71.0
45.0

# Exercice 7

Cette fois-ci nous avons les quantités achetées ainsi que le prix unitaires pour chacun des éléments

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>1</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>john</th>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

```py
[20, 5, 3]
````

- calculez le montant total par personne
- calculez le montant total par produit

<br>

In [38]:
# par personne
arr = np.array([
    [1, 4, 2],
    [3, 5, 7],
    [5, 4, 4]
])
price = np.array([20, 5, 3])

## produit (interieur/inner) matriciel: 
np.dot(arr, price)

array([ 46, 106, 132])

In [39]:
# slower
## produit matriciel
print(arr*price)
print('-'*50)
print((arr*price).sum(axis=-1)) # axis = -1 : dernier axe

[[ 20  20   6]
 [ 60  25  21]
 [100  20  12]]
--------------------------------------------------
[ 46 106 132]

In [40]:
# par produit


print(arr*price)
print('-'*50)
print((arr*price).sum(axis=0)) # axis = -1 : dernier axe

## produit matriciel avec "Einstein summation"
#np.einsum('i, ji->i', price, arr)
np.einsum('ij, j->j', arr, price)

[[ 20  20   6]
 [ 60  25  21]
 [100  20  12]]
--------------------------------------------------
[180  65  39]

array([180,  65,  39])